# KISS-ICP configuration for Water Linked Sonar 3D-15

kiss_icp_node:
  ros__parameters:
    # TF configuration
    # base_frame: ""
    lidar_odom_frame: "odom"
    publish_odom_tf: True
    invert_odom_tf: True
    position_covariance: 0.1
    orientation_covariance: 0.1

    use_external_odom: True
    external_odom_topic: "/okvis_odometry"
    
    # Soft prior tuning
    soft_prior:
      max_alpha: 0.3
      min_alpha: 0.05
      high_trust_variance: 0.001
      low_trust_variance: 0.1

    # Core KISS-ICP parameters
    data:
      deskew: False             # 
      max_range: 10.0           # 10m for Water Linked 3D-15 
      min_range: 0.3            # reject close returns 

    mapping:
      voxel_size: 0.15          # ~max_range/100
      max_points_per_voxel: 20

    adaptive_threshold:
      initial_threshold: 2.0
      min_motion_th: 0.05       # lower threshold for slow motion

    registration:
      max_num_iterations: 500
      convergence_criterion: 0.0001
      max_num_threads: 0
